# Generated by Django 5.2.3 on 2025-07-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptify_app', '0002_alter_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('model', 'model'), ('user', 'user')], max_length=15),
        ),
    ]
