# Generated by Django 5.1.3 on 2026-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aichatsession_airequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
