# Generated by Django 5.1.3 on 2026-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_airequest_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
