# Generated by Django 5.1.3 on 2026-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_airequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
