# Generated by Django 5.1.3 on 2026-01-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_airequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
