# Generated by Django 5.1.3 on 2026-01-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_airequest_message_alter_airequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
