# Generated by Django 5.1.3 on 2026-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aichatsession_messages_aichatsession_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
