# Generated by Django 5.1.3 on 2026-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aichatsession_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
